# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(632, 277)
        self.btn = QtWidgets.QPushButton(Dialog)
        self.btn.setGeometry(QtCore.QRect(10, 240, 611, 31))
        self.btn.setObjectName("btn")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(150, 20, 20, 201))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(34, 76, 91, 31))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 134, 141, 31))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 190, 111, 31))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.EP = QtWidgets.QTextEdit(Dialog)
        self.EP.setGeometry(QtCore.QRect(180, 13, 441, 41))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(14)
        self.EP.setFont(font)
        self.EP.setObjectName("EP")
        self.IB = QtWidgets.QTextEdit(Dialog)
        self.IB.setGeometry(QtCore.QRect(180, 70, 441, 41))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(14)
        self.IB.setFont(font)
        self.IB.setObjectName("IB")
        self.SA = QtWidgets.QTextEdit(Dialog)
        self.SA.setGeometry(QtCore.QRect(180, 130, 441, 41))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(14)
        self.SA.setFont(font)
        self.SA.setObjectName("SA")
        self.FA = QtWidgets.QTextEdit(Dialog)
        self.FA.setGeometry(QtCore.QRect(180, 190, 441, 41))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(14)
        self.FA.setFont(font)
        self.FA.setObjectName("FA")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn.setText(_translate("Dialog", "Create"))
        self.label.setText(_translate("Dialog", "EntryPoint"))
        self.label_2.setText(_translate("Dialog", "ImageBase"))
        self.label_3.setText(_translate("Dialog", "Section Aligment"))
        self.label_4.setText(_translate("Dialog", "File Aligmnet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
